### ISSUE TITLE
Remove underline from links

### ISSUE THREAD

**Issue by Blindnomore** [redacsio/dev#11]
Убрать подчеркивание с ссылки “Авторизуйтесь”

![screenshot 2018-10-09 at 00 11 11](https://user-images.githubusercontent.com/4731287/46633906-d9b65a80-cb57-11e8-98c1-d4839f7879eb.png)

Дизайн макет: 
![screenshot 2018-10-09 at 00 11 37](https://user-images.githubusercontent.com/4731287/46633934-ec309400-cb57-11e8-8a20-9c5df52d1d69.png)

**Comment by DelMaradinho** [comment]
link text decoration removed
