### ISSUE TITLE
Button font

### ISSUE THREAD

**Issue by Blindnomore** [redacsio/dev#9]
Обновить в соответствии с дизайн макетом шрифт на кнопке “Присоединится”

**Как сейчас:** 
![screenshot 2018-10-09 at 00 06 43](https://user-images.githubusercontent.com/4731287/46633732-3b29f980-cb57-11e8-8406-ed24dac0aea4.png)

**Как должно:** 
![screenshot 2018-10-09 at 00 07 52](https://user-images.githubusercontent.com/4731287/46633779-6280c680-cb57-11e8-980a-72faa7d57774.png)

**Comment by DelMaradinho** [comment]
done
